name: flutter_icons
description: Customizable Icons for Flutterï¼Œyou can use with over 15K+ icons in your flutter project
version: 4.1.0-nullsafety.0
author: Sascha Heim<developers@think-big-company.com>
homepage: https://github.com/ThinkBIG-Company/flutter-icons.git

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  recase: ^4.0.0-nullsafety
  flutter_test:
    sdk: flutter
  version: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
      - family: AntDesign
        fonts:
          - asset: fonts/AntDesign.ttf
      - family: AntDesign-Filled
        fonts:
          - asset: fonts/AntDesign-Filled.ttf
      - family: AntDesign-Outlined
        fonts:
          - asset: fonts/AntDesign-Outlined.ttf
      - family: Brandico
        fonts:
          - asset: fonts/Brandico.ttf
      - family: Elusive-Icons
        fonts:
          - asset: fonts/Elusiveicons.ttf
      - family: Entypo
        fonts:
          - asset: fonts/Entypo.ttf
      - family: EvilIcons
        fonts:
          - asset: fonts/EvilIcons.ttf
      - family: Feather
        fonts:
          - asset: fonts/Feather.ttf
      - family: FontAwesome
        fonts:
          - asset: fonts/FontAwesome.ttf
      - family: FontAwesome5_Brands
        fonts:
          - asset: fonts/FontAwesome5_Brands.ttf
      - family: FontAwesome5
        fonts:
          - asset: fonts/FontAwesome5_Regular.ttf
      - family: FontAwesome5_Solid
        fonts:
          - asset: fonts/FontAwesome5_Solid.ttf
      - family: Fontelico
        fonts:
          - asset: fonts/Fontelico.ttf
      - family: Fontisto
        fonts:
          - asset: fonts/Fontisto.ttf
      - family: Foundation
        fonts:
          - asset: fonts/Foundation.ttf
      - family: Iconic
        fonts:
          - asset: fonts/Iconic.ttf
      - family: Ionicons
        fonts:
          - asset: fonts/Ionicons.ttf
      - family: Linearicons-Free
        fonts:
          - asset: fonts/Linearicons-Free.ttf
      - family: Linecons
        fonts:
          - asset: fonts/Linecons.ttf
      - family: Maki
        fonts:
          - asset: fonts/Maki.ttf
      - family: MaterialCommunityIcons
        fonts:
          - asset: fonts/MaterialCommunityIcons.ttf
      - family: MaterialIcons-Baseline
        fonts:
          - asset: fonts/MaterialIcons-Baseline.ttf
      - family: MaterialIcons-Outline
        fonts:
          - asset: fonts/MaterialIcons-Outline.ttf
      - family: MaterialIcons-Round
        fonts:
          - asset: fonts/MaterialIcons-Round.ttf
      - family: MaterialIcons-Sharp
        fonts:
          - asset: fonts/MaterialIcons-Sharp.ttf
      - family: MaterialIcons-TwoTone
        fonts:
          - asset: fonts/MaterialIcons-TwoTone.ttf
      - family: Meteocons
        fonts:
          - asset: fonts/Meteocons.ttf
      - family: MfgLabs
        fonts:
          - asset: fonts/MfgLabs.ttf
      - family: ModernPictograms
        fonts:
          - asset: fonts/ModernPictograms.ttf
      - family: Octicons
        fonts:
          - asset: fonts/Octicons.ttf
      - family: RpgAwesome
        fonts:
          - asset: fonts/RpgAwesome.ttf
      - family: SimpleLineIcons
        fonts:
          - asset: fonts/SimpleLineIcons.ttf
      - family: Typicons
        fonts:
          - asset: fonts/Typicons.ttf
      - family: WeatherIcons
        fonts:
          - asset: fonts/WeatherIcons.ttf
      - family: WebSymbols
        fonts:
          - asset: fonts/WebSymbols.ttf
      - family: Zocial
        fonts:
          - asset: fonts/Zocial.ttf
